---
coverage:
  status:
    project:
      default:
        enabled: true
        target: "80%"
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        enabled: true
        target: "50%"
        set_pending: yes
        if_not_found: success
        if_ci_failed: error
